export const TSConfig = {
  compilerOptions: {
    target: 'es2017',
    module: 'esnext',
    strict: true,
    declaration: true,
    jsx: 'react',
    jsxFactory: 'h',
    importHelpers: true,
    moduleResolution: 'node',
    experimentalDecorators: true,
    noUnusedLocals: true,
    noUnusedParameters: true,
    esModuleInterop: true,
    allowSyntheticDefaultImports: true,
    allowUnreachableCode: false,
    preserveSymlinks: true,
    emitDecoratorMetadata: true,
    skipLibCheck: true,
    allowJs: true,
    sourceMap: true,
    inlineSourceMap: true,
    inlineSources: true,
    baseUrl: '.',
    lib: ['esnext', 'dom', 'dom.iterable', 'es2018'],
  },
  exclude: ['node_modules', '.bit'],
  include: ['types/jsx.d.ts'],
};
