name: Test and Export

on: [pull_request]
env:
  BIT_TOKEN: ${{ secrets.BIT_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm config set @bit:registry https://node.bit.dev && npm config list && npm install
      - name: Install bit-bin
        run: sudo npm install bit-bin@14.8.8 -g --unsafe-perm
      - name: bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token ${{ env.BIT_TOKEN }}
          bit config
      - name: run tests
        run: npm run test
